name: Gamma - Build
on:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./folder

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: |
          yarn install && yarn test:ci
